### ISSUE TITLE
Switch from Redux to MobX

### ISSUE THREAD

**Issue by HaileyJang** [pioneers/dawn#111]
Switch from Redux to MobX. 

- [x] alert.ts
- [x] console.ts
- [x] editor.ts
- [ ] field.ts
- [x] gamepads.ts
- [x] info.ts
- [ ] peripherals.ts
- [x] settings.ts
- [x] timerStore.ts

**Comment by ewc340** [comment]
We can hold off on peripherals since that one may be a bit more complicated.

**Comment by ewc340** [comment]
We can also just convert everything to using stores first and not touch the components yet.
