### ISSUE TITLE
[Initiative] Convert and refactor actions and reducers

### ISSUE THREAD

**Issue by ewc340** [pioneers/dawn#12]
- [x] Remove export defaults
- [x] Follow consistent file naming (i.e. in the reducers folder some some file names start with uppercase while others don't)
- [x] Create new Typescript interfaces for reducers
- [x] Provide more specific types to function arguments

**Comment by ewc340** [comment]
@HaileyJang I'll create an example first so you can follow.

**Comment by AVSurfer123** [comment]
Closed in #16
