### ISSUE TITLE
Update react-bootstrap

### ISSUE THREAD

**Issue by ewc340** [pioneers/dawn#56]
Our current version of react-bootstrap (0.32.0), which runs with Bootstrap 3, is pretty outdated so it doesn't support Typescript. We need to upgrade to an updated version (that uses Bootstrap 4) - a previous attempt in simply updating to the latest version caused build errors, so some refactoring will be required in the components to comply with Bootstrap 4.

**Comment by ewc340** [comment]
Some notes:
[Bootstrap v3](https://react-bootstrap-v3.netlify.app/components/navbar/)
[Some notes on grid in bootstrap v3](https://rsuitejs.com/components/grid)
[Bootstrap v4 and migrating](https://react-bootstrap.netlify.app/migrating/#glyphicon)

**Comment by MeshanKhosla** [comment]
Thomas - Dashboard and Dnav
Meshan - ConfigBox and ConsoleOutput
Saketh - Gamepad and GamepadList
Andrew - UpdateBox
