### ISSUE TITLE
Research alternatives to Redux state management

### ISSUE THREAD

**Issue by ewc340** [pioneers/dawn#90]
Currently we are using Redux but there is a lot of boilerplate and is just hard for beginners to learn in general, we should consider checking if we can reduce the amount of boilerplate somehow or move to another state management library.

Current state management library we are using:
- Redux (https://redux.js.org)

Some alternatives:
- mobx (https://mobx.js.org/README.html)
- React contexts (part of React and not an external library) 

Overall factors to consider for the new library are ideally being able to refactor from our existing codebase as easily as possible and simplicity in using and learning the library.

**Comment by uthmanmomen13** [comment]
Found MobX
